### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by coolKeen** [lisiyao21/AnimeInterp#18]
Nice work!
Do you have any plan for releasing training code?
Thanks in advance!

**Comment by coolKeen** [comment]
Another question:
The network in SGM (i.e. vgg) is the pretrained model provided by Pytorch, right？

**Comment by lisiyao21** [comment]
Sorry for late reply. 

Since the training code base is related to a business project of SenseTime (but not for anime), I'd better not release it. Sorry for that. But it is really not hard to implement one just imitating the test code.

For the second question, yes, we used the PyTorch VGG19.

Thanks for your interest.
